---
"Cloudflare": https://www.cloudflarestatus.com
"Datadog": https://status.datadoghq.com
"GitHub": https://www.githubstatus.com
"Sendgrid": https://status.sendgrid.com
"Trello": https://trello.status.atlassian.com
"Zoom": https://status.zoom.us
"Litmus": https://status.litmus.com
